name: app
runtime:
  name: python
  options:
    virtualenv: ../../.venv
description: app deployment
backend:
  url: s3://ariel-pulumi-state
template:
  config:
    aws:profile:
      default: ariel
    aws:region:
      default: us-east-1
